In [1]:
import numpy as np
from scipy.stats import beta

### The concept
TBD

Consider a dataset X containing samples x, a generator G and k number of discriminators D_i


Let's assign k beta distributios to each sample to model the probability of succesful classification (true positive, false negative)

In [51]:
class DataHolder(object):
    
    def __init__(self,n_clusters,X):
        #sucess index = 0
        self.X = X
        self.n_clusters = n_clusters
        self.stats = np.ones((len(X),n_clusters,2),dtype = int)
    
    def update(self,sample_index,cluster_index,outcome):
        self.stats[sample_index,cluster_index,outcome]+=1
    
    def assign(self):
        assignment=[]
        for sample in self.stats:
            assignment.append(np.argmax([beta.rvs(*component) for component in sample]))
        
        assignment = np.asarray(assignment)
        assignment_indices = [np.where(assignment == k)[0] for k in range(self.n_clusters)]
        assignment_data  = [self.X[indices] for indices in assignment_indices]
        return assignment_indices,assignment_data
        
    

In [66]:
x=np.ones((100,5))*np.arange(0,100).reshape(-1,1)
dh = DataHolder(n_clusters = 3, X = x)

In [80]:

for _ in range(200):
    indices, data = dh.assign()
    dh.update(indices[0], 0*np.ones_like(indices[0],dtype = int), np.zeros_like(indices[0],dtype = int) )


[array([[ 0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.,  9.],
        [10., 10., 10., 10., 10.],
        [11., 11., 11., 11., 11.],
        [12., 12., 12., 12., 12.],
        [13., 13., 13., 13., 13.],
        [14., 14., 14., 14., 14.],
        [15., 15., 15., 15., 15.],
        [16., 16., 16., 16., 16.],
        [17., 17., 17., 17., 17.],
        [18., 18., 18., 18., 18.],
        [19., 19., 19., 19., 19.],
        [20., 20., 20., 20., 20.],
        [21., 21., 21., 21., 21.],
        [22., 22., 22., 22., 22.],
        [23., 23., 23., 23., 23.],
        [24., 24., 24., 24., 24.],
        [25., 25., 25., 25., 25.],
        [26., 26., 26., 26., 26.],
        [27., 27., 27., 27., 27.],
        [28., 28., 2

In [76]:
indices[0]

array([ 4,  6,  7, 13, 15, 16, 19, 20, 21, 26, 34, 35, 36, 41, 44, 54, 55,
       58, 59, 64, 66, 67, 69, 70, 71, 75, 84, 85, 86, 89, 90, 91, 95, 97,
       99], dtype=int64)

In [98]:
dh.update(19,0,1)

In [85]:
beta.rvs([5000,5000])

0.49902892917203157

In [104]:
dh.stats[0,2]

array([1, 1])

In [108]:
test = np.ones((10,3,2),dtype = int)

In [125]:
np.random.randint(0,3,10)

array([1, 2, 0, 1, 1, 0, 1, 2, 1, 1])

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 0])

In [128]:
test[np.arange(0,10),np.random.randint(0,3,10),np.random.randint(0,2,10)] += 1

In [129]:
test

array([[[1, 1],
        [1, 1],
        [2, 1]],

       [[1, 1],
        [1, 1],
        [2, 1]],

       [[1, 1],
        [2, 1],
        [1, 1]],

       [[2, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [2, 1]],

       [[1, 2],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [2, 1],
        [1, 1]],

       [[2, 1],
        [1, 1],
        [1, 1]],

       [[2, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 2],
        [1, 1]]])